### ISSUE TITLE
Horizontal scroll bar is thicker than vertical scroll bar

### ISSUE THREAD

**Issue by lee-dohm** [dmackerman/atom-soda-light-ui#2]
At least on OS X:

![screen shot 2014-10-03 at 5 28 41 am](https://cloud.githubusercontent.com/assets/1038121/4505687/02d18964-4af9-11e4-801e-cf47d15ab779.png)

**Comment by dmackerman** [comment]
Weird. I haven't taken a look at this in a while TBH, but maybe this weekend I'll have a look.

**Comment by lee-dohm** [comment]
Awesome! Thanks 😎
